# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etemplate.proto\"2\n\x0cHelloRequest\x12\x14\n\x0cHelloRequest\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"&\n\rGoodbye_reply\x12\x15\n\rGoodbye_reply\x18\x01 \x01(\t\"0\n\x0bHelloStream\x12\x13\n\x0bHelloStream\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"(\n\x0eGoodbye_stream\x12\x16\n\x0eGoodbye_stream\x18\x01 \x01(\t\"&\n\rHelloRepeated\x12\x15\n\rHelloRepeated\x18\x01 \x03(\t2\xa4\x02\n\x08template\x12,\n\tunary_rpc\x12\r.HelloRequest\x1a\x0e.Goodbye_reply\"\x00\x12:\n\x14server_streaming_rpc\x12\r.HelloRequest\x1a\x0f.Goodbye_stream\"\x00\x30\x01\x12\x38\n\x14\x63lient_streaming_rpc\x12\x0c.HelloStream\x1a\x0e.Goodbye_reply\"\x00(\x01\x12\x42\n\x1b\x62idirectional_streaming_rpc\x12\x0c.HelloStream\x1a\x0f.Goodbye_stream\"\x00(\x01\x30\x01\x12\x30\n\x0crepeated_rpc\x12\x0e.HelloRepeated\x1a\x0e.Goodbye_reply\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_GOODBYE_REPLY = DESCRIPTOR.message_types_by_name['Goodbye_reply']
_HELLOSTREAM = DESCRIPTOR.message_types_by_name['HelloStream']
_GOODBYE_STREAM = DESCRIPTOR.message_types_by_name['Goodbye_stream']
_HELLOREPEATED = DESCRIPTOR.message_types_by_name['HelloRepeated']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

Goodbye_reply = _reflection.GeneratedProtocolMessageType('Goodbye_reply', (_message.Message,), {
  'DESCRIPTOR' : _GOODBYE_REPLY,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:Goodbye_reply)
  })
_sym_db.RegisterMessage(Goodbye_reply)

HelloStream = _reflection.GeneratedProtocolMessageType('HelloStream', (_message.Message,), {
  'DESCRIPTOR' : _HELLOSTREAM,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:HelloStream)
  })
_sym_db.RegisterMessage(HelloStream)

Goodbye_stream = _reflection.GeneratedProtocolMessageType('Goodbye_stream', (_message.Message,), {
  'DESCRIPTOR' : _GOODBYE_STREAM,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:Goodbye_stream)
  })
_sym_db.RegisterMessage(Goodbye_stream)

HelloRepeated = _reflection.GeneratedProtocolMessageType('HelloRepeated', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPEATED,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:HelloRepeated)
  })
_sym_db.RegisterMessage(HelloRepeated)

_TEMPLATE = DESCRIPTOR.services_by_name['template']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=18
  _HELLOREQUEST._serialized_end=68
  _GOODBYE_REPLY._serialized_start=70
  _GOODBYE_REPLY._serialized_end=108
  _HELLOSTREAM._serialized_start=110
  _HELLOSTREAM._serialized_end=158
  _GOODBYE_STREAM._serialized_start=160
  _GOODBYE_STREAM._serialized_end=200
  _HELLOREPEATED._serialized_start=202
  _HELLOREPEATED._serialized_end=240
  _TEMPLATE._serialized_start=243
  _TEMPLATE._serialized_end=535
# @@protoc_insertion_point(module_scope)
